version: "3.9"

services:
    viet-chat:
        image: localhost/nodejs22151:latest
        container_name: viet-chat
        command: tail -f /dev/null
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /data/max.dh.kuo_data:/app

        working_dir: /app
        ports:
            - "8884:8884"
        restart: unless-stopped
